# Generated by Django 6.0.6 on 2026-06-20 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('jornada', models.CharField(choices=[('diurno', 'Diurno'), ('nocturno', 'Nocturno'), ('virtual', 'Virtual')], max_length=10, verbose_name='Jornada')),
                ('semestre', models.CharField(choices=[('1', 'Semestre 1'), ('2', 'Semestre 2'), ('3', 'Semestre 3'), ('4', 'Semestre 4'), ('5', 'Semestre 5'), ('6', 'Semestre 6'), ('7', 'Semestre 7'), ('8', 'Semestre 8'), ('9', 'Semestre 9'), ('10', 'Semestre 10')], max_length=2, verbose_name='Semestre')),
                ('programa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiantes', to='core.programa', verbose_name='Programa')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'ordering': ['nombre'],
            },
        ),
    ]
